# .github/workflows/deploy.yaml

name: Hexo Deploy

on:
  push:
    branches:
    - master

jobs:
  build:
    # 配置运行该 worykflow 的系统
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    env:
      NODE_VERSION: '16'

    steps:
      - name: Checkout source
      - uses: actions/checkout@v2
        with:
          ref: master

      # 配置 Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn

      - name: Setup Hexo
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.HEXO_BLOG_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.email "s22539634@aliyun.com"
          git config --global user.name "s-xianyu"
          yarn install hexo-cli -g
          yarn install

      - name: Deploy
        run: |
          hexo clean
          hexo deploy